// Register user
POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "amr11@g.com",
    "username": "amr",
    "password": "1234"
}

###
// Login user

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "amr12@g.com",
    "password": "1234"
}

###
// Home Page

GET http://localhost:3000/

###
// Logout user

POST http://localhost:3000/logout

###
// Create Project

POST http://localhost:3000/project/create
Content-Type: application/json

{
    "teamId": 3,
    "projectName": "newProject"
}

###
// Join Project using uuid

POST http://localhost:3000/project/join
Content-Type: application/json

{
    "uuid": "d742cdcd-4802-41e3-9f95-f5bb25a7c774"
}
###
GET http://localhost:3000/project?teamId=3
###
GET http://localhost:3000/project/5
###
// List members of team

GET http://localhost:3000/team/1/member
###
post  http://localhost:3000/project/delete/5


//______________________________________________________

###
// Register user

POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "s12@g.com",
    "username": "salma",
    "password": "1234"
}

###
// Login user

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "s12@g.com",
    "password": "1234"
}

###
// Create team
//0eb7f723
POST http://localhost:3000/team
Content-Type: application/json

{
    "teamName": "t"
}

###
// Add member to team

PUT http://localhost:3000/team/5/member
Content-Type: application/json

{
    "memberEmail": "s@g.com",
    "teamId": 5
}

###
// Get code of team

PUT http://localhost:3000/team/code
Content-Type: application/json

{
    "teamId": 53
}

###
// Join a team

PUT http://localhost:3000/team/join
Content-Type: application/json

{
    "token": "2f353502"
}


###
// Update team

PUT http://localhost:3000/team
Content-Type: application/json

{
    "newName": "sssss",
    "teamId": 9
}

###
// Get all users of the team

GET http://localhost:3000/team/5/member
Content-Type: application/json


###
// List all teams of the user

GET http://localhost:3000/team
Content-Type: application/json

###

// Delete member from team
DELETE  http://localhost:3000/team/5/member
Content-Type: application/json

{
    "memberEmail": "s@g.com"
    }


###
// Delete team

DELETE  http://localhost:3000/team
Content-Type: application/json

{
    "teamId": 29
}

###

POST http://localhost:3000/project/create
Content-Type: application/json

{
    "teamId": "2",
    "projectName": "project2"
}

###



// Create Project

POST http://localhost:3000/project/create
Content-Type: application/json

{
    "teamId": 30,
    "projectName": "newProject"
}

###

// listProjects

GET http://localhost:3000/project?teamId=12
Content-Type: application/json
###